FROM fedora:32

RUN dnf -y install \
        alsa-lib-devel \
        autoconf \
        cups-devel \
        diffutils \
        file \
        findutils \
        fontconfig-devel \
        gcc \
        git \
        g++ \
        libffi-devel \
        libXi-devel \
        libXrandr-devel \
        libXrender-devel \
        libXt-devel \
        libXtst-devel \
        make \
        python \
        unzip \
        which \
        zip
