build-fedora32:
	docker build -t fedora32 -f Dockerfile.fedora32

run-fedora32:
  docker run -it --storage-opt size=20G fedora32 /bin/bash

build-centos7:
	docker build -t centos7 -f Dockerfile.centos7

run-centos7:
  docker run -it --storage-opt size=20G fedora /bin/bash

