# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B install --file pom.xml
      env:
        MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"
    - name: Test with Labs 20.1 build example
      uses: jbangdev/jbang-action@v0.52.0
      with:
        script: examples/labs_20_1.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
    - name: Test with Labs 20.3 build example
      uses: jbangdev/jbang-action@v0.52.0
      with:
        script: examples/labs_20_3.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
    - name: Test with JDK build example
      uses: jbangdev/jbang-action@v0.52.0
      with:
        script: examples/jdk_jdk.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
