# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
        restore-keys: |
          ${{ runner.os }}-jbang-
    - name: Test with JBang
      uses: jbangdev/jbang-action@v0.52.0
      with:
        script: jbang/labs_20_1.java
        jbangargs: -Dqollider.version=999-SNAPSHOT
      env:
        JBANG_REPO: /root/.jbang/repository
