# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B install --file pom.xml
      env:
        MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"
    - name: Compile example to build Graal
      uses: jbangdev/jbang-action@v0.56.0
      with:
        script: examples/graal.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
    - name: Compile example to build Infinispan Quarkus native server
      uses: jbangdev/jbang-action@v0.56.0
      with:
        script: examples/infinispan_native.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
    - name: Compile example to build JDK
      uses: jbangdev/jbang-action@v0.56.0
      with:
        script: examples/jdk.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
    - name: Compile example to build Mandrel
      uses: jbangdev/jbang-action@v0.56.0
      with:
        script: examples/mandrel.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
    - name: Compile example to build Quarkus
      uses: jbangdev/jbang-action@v0.56.0
      with:
        script: examples/quarkus.java
        jbangargs: build -Dqollider.version=999-SNAPSHOT --verbose
      env:
        JBANG_REPO: "${{ github.workspace }}/repository"
