name: Run examples

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B install --file pom.xml
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"
      - name: Test with Labs 20.1 build example
        uses: jbangdev/jbang-action@v0.52.0
        with:
          script: examples/labs_20_1.java
          jbangargs: -Dqollider.version=999-SNAPSHOT --verbose
        env:
          JBANG_REPO: "${{ github.workspace }}/repository"
